### PR TITLE
update to node10x

### PR DESCRIPTION
**Pull request by zmully**
I'm not sufficiently familiar with this stack to understand why the tests were failing when run with the fake URL `aws.response.com` which doesn't resolve. I switched the tests to use a fake  `api.mapbox.com` URL that does resolve and the tests pass, but someone else should definitely look into the test failures (i.e. should this DNS lookup have been mocked as well, or did the original URL just happen to be valid at one point?) 

/cc @mapbox/platform 

```
Error: getaddrinfo ENOTFOUND aws.response.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'aws.response.com'
}
```

### CODE REVIEW

**Comment by jakepruitt** [comment]
> or did the original URL just happen to be valid at one point?

I think a once-valid DNS name would be my guess @zmully - I think this looks good!

**Comment by drboyer** [comment]
We should probably mock the requests being made by the Response module; we do this in other repositories where we set up CloudFormation Custom Resources.

@zmully do you mind at least ticketing this as something we should pick up? No need to derail this PR with that if you don't want to.

**Comment by zmully** [comment]
:man_shrugging: I don't know @drboyer, it's up to the code owners/people in the know to decide if this PR needs further mocking or not. This default vpc function is critical, right?

**Comment by vsmart** [comment]
@zmully Can you update the changelog with a note on this release?

**Pull request merged**
